replicas: 1
image:
    repository: l4rm4nd/menufic
    tag: latest
    pullPolicy: IfNotPresent

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    annotations: {}
    host: menufic.example.com
    tls:
        enabled: false
        secretName: ""

database:
    url: "postgresql://user:password@localhost:34837/menufic_db"

# Next Auth GitHub Provider
# The callback url must be http://127.0.0.1:3000/api/auth/callback/github
# Adjust protocol, IP and port to your setup
github:
    clientId: ""
    secret: ""

# Next Auth Google Provider
google:
    clientId: ""
    secret: ""

imagekit:
    # Please create an account in https://imagekit.io and use the generated keys here
    url: "https://ik.imagekit.io/xxxx"
    baseFolder: "menufic-local"
    publicKey: ""
    privateKey: ""

nextauth:
    url: "http://localhost:3000"
    # You can generate the secret via 'openssl rand -base64 32' on Linux
    # More info: https://next-auth.js.org/configuration/options#secret
    secret: ""

web3forms:
    # Contact us form relies on https://web3forms.com
    apiKey: ""

sentry:
    publicDsn:
    org:
    project:
    authToken:

appConfig:
    usageLimits:
        maxRestaurantsPerUser: 5
        maxMenusPerRestaurant: 5
        maxCategoriesPerMenu: 10
        maxMenuItemsPerCategory: 20
        maxBannersPerRestaurant: 5
    # For sample menu shown in landing page
    sampleMenuId: 1
    # For contact us and terms & conditions page
    contactEmail: "example@mail.com"
    # Deployed URL used for redirection purposes
    publicUrl: "https://menufic.example.com"
