apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}-secret-env
type: Opaque
data:
  GITHUB_CLIENT_SECRET: {{ .Values.github.secret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.secret }}
  IMAGEKIT_PRIVATE_KEY: {{ .Values.imagekit.privateKey }}
  NEXTAUTH_SECRET: {{ .Values.nextauth.secret }}
  SENTRY_AUTH_TOKEN: {{ .Values.sentry.authToken }}